@startuml
start
:Получение входных данных:\nD (дни), P (путешественники),\nмассив expenses, курсы валют rates;
:Инициализация C_total = 0;
repeat
  :Взять следующую категорию e из expenses;
  if () then (ежедневный расход)
    :C_e = e.value × D × P;
  else (фиксированный расход)
    :C_e = e.value × P;
  endif
  :Конвертация в целевую валюту;
  :C_total += C_e_target;
repeat while () is (ещё категории)
-> категории закончились;
:Построение детализации по дням;
:Формирование итоговой структуры \n(итоговая сумма, разбивка по категориям);
stop
@enduml